directories:
  output: dist-electron-out
  buildResources: build
appId: com.ch-ui.desktop
productName: deebee
files:
  - filter:
      - dist/**/*
      - out/**/*
linux:
  target: AppImage
  category: Development
electronVersion: 42.4.0
