/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DashboardsTemplatesRouteImport } from './routes/dashboards/templates'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards/$dashboardId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsTemplatesRoute = DashboardsTemplatesRouteImport.update({
  id: '/dashboards/templates',
  path: '/dashboards/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/settings': typeof SettingsRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/dashboards/': typeof DashboardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/settings': typeof SettingsRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/dashboards': typeof DashboardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/settings': typeof SettingsRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/dashboards/': typeof DashboardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/logs'
    | '/metrics'
    | '/settings'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/dashboards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/logs'
    | '/metrics'
    | '/settings'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/dashboards'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/logs'
    | '/metrics'
    | '/settings'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/dashboards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  SettingsRoute: typeof SettingsRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  DashboardsTemplatesRoute: typeof DashboardsTemplatesRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/templates': {
      id: '/dashboards/templates'
      path: '/dashboards/templates'
      fullPath: '/dashboards/templates'
      preLoaderRoute: typeof DashboardsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  SettingsRoute: SettingsRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  DashboardsTemplatesRoute: DashboardsTemplatesRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
